I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dialogue.rpy", line 134, in script
    $gamesWon = open("gamesWon.txt", "r+")
  File "game/dialogue.rpy", line 134, in <module>
    $gamesWon = open("gamesWon.txt", "r+")
IOError: [Errno 2] No such file or directory: u'gamesWon.txt'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dialogue.rpy", line 134, in script
    $gamesWon = open("gamesWon.txt", "r+")
  File "C:\Users\RIDENTEM\Downloads\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\RIDENTEM\Downloads\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/dialogue.rpy", line 134, in <module>
    $gamesWon = open("gamesWon.txt", "r+")
IOError: [Errno 2] No such file or directory: u'gamesWon.txt'

Windows-8-6.2.9200
Ren'Py 7.1.1.929
checkOnMyHeart 1.0
Thu Nov 29 21:31:24 2018
